name: deploy-to-test

on:
  push:
    branches: [ master-dev ]
  pull_request:
    branches: [ master-dev ]

jobs:
  deploy-to-test:

    runs-on: ubuntu-latest

    steps:
    - name: Deploy to Test
      uses: appleboy/ssh-action@master
      with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: 'cd /home/u793801228/domains/kodatik.net/public_html && chmod +x ./server_deploy.sh && ./server_deploy.sh'
